add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                    
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗
# Cool stuff 󰜥   

# Don't print a new line at the start of the prompt
format = """
$username$hostname  $cmd_duration 󰜥 $directory$git_branch$git_status
$character"""

[character]
success_symbol = "[  ](bold fg:#89ddff)"
error_symbol = "[  ](bold fg:#f7768e)"
vimcmd_symbol = "[  ❮](bold fg:#bb9af7)"
vimcmd_visual_symbol = "[  ❮](bold fg:#b4f9f8)"
vimcmd_replace_symbol = "[  ❮](bold fg:#f7768e)"
vimcmd_replace_one_symbol = "[  ❮](bold fg:#f7768e)"

[package]
disabled = true

[git_branch]
style = "bg:#9abdf5"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = "…"
format = " 󰜥 [](bold fg:#9abdf5)[$symbol $branch(:$remote_branch)](fg:#1a1b26 bg:#9abdf5)[](bold fg:#9abdf5)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold #f7768e)"

[git_status]
style = "bg:#9abdf5 fg:#1a1b26"
format = ' [](bold fg:#9abdf5)[$all_status$ahead_behind]($style)[](bold fg:#9abdf5)'
conflicted = " "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "󰋗 "
stashed = "󰏗 "
modified = "󰏫 "
staged = '[++\($count\)](bold fg:#1a1b26 bg:#9abdf5) '
renamed = "󰑕 "
deleted = "󰆴 "

[hostname]
ssh_only = false
format = "[•$hostname](bg:#9abdf5 bold fg:#1a1b26)[](bold fg:#9abdf5)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold #b4f9f8"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:#9abdf5 fg:#1a1b26"
style_root = "#f7768e bold"
format = "[](bold fg:#9abdf5)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = "  "
read_only = "  "
style = "bg:#89ddff fg:#1a1b26"
truncation_length = 6
truncation_symbol = " ••/"
format = '[](bold fg:#89ddff)[󰉋 $path]($style)[](bold fg:#89ddff)'

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[cmd_duration]
min_time = 0
format = '[](bold fg:#b4f9f8)[󰪢 $duration](bold bg:#b4f9f8 fg:#1a1b26)[](bold fg:#b4f9f8)'
