windowrule = opacity $windowOpacity override, match:fullscreen 0

windowrule = opaque on, match:class ^(foot|equibop|org\.quickshell|imv|swappy)$

windowrule = float on, match:class ^(guifetch|yad|zenity|wev|org\.gnome\.FileRoller|file-roller|blueman-manager|com\.github\.GradienceTeam\.Gradience|feh|imv|system-config-printer|org\.quickshell)$

windowrule = float on, match:class ^(foot)$, match:title ^(nmtui)$
windowrule = size 60% 70%, match:class ^(foot)$, match:title ^(nmtui)$
windowrule = center on, match:class ^(foot)$, match:title ^(nmtui)$

windowrule = float on, match:class ^(org\.gnome\.Settings)$
windowrule = size 70% 80%, match:class ^(org\.gnome\.Settings)$

windowrule = float on, match:class ^(org\.pulseaudio\.pavucontrol|yad-icon-browser)$
windowrule = size 60% 70%, match:class ^(org\.pulseaudio\.pavucontrol|yad-icon-browser)$

windowrule = float on, match:class ^(nwg-look)$
windowrule = size 50% 60%, match:class ^(nwg-look)$

windowrule = workspace special:sysmon, match:class ^(btop)$
windowrule = workspace special:music, match:class ^(feishin|Spotify|Supersonic|Cider)$
windowrule = workspace special:music, match:initial_title ^(Spotify( Free)?)$
windowrule = workspace special:communication, match:class ^(discord|equibop|vesktop|whatsapp)$
windowrule = workspace special:todo, match:class ^(Todoist)$

windowrule = float on, match:title ^(Select|Open)( a)? (File|Folder)(s)?$
windowrule = float on, match:title ^(File (Operation|Upload)( Progress)?)$
windowrule = float on, match:title ^(.* Properties)$
windowrule = float on, match:title ^(Save As)$
windowrule = float on, match:title ^(Library)$

windowrule = float on, match:title ^(Picture([ -])in([ -])[Pp]icture)$
windowrule = pin on, match:title ^(Picture([ -])in([ -])[Pp]icture)$
windowrule = keep_aspect_ratio on, match:title ^(Picture([ -])in([ -])[Pp]icture)$

windowrule = rounding 10, match:class ^(steam)$, match:title ^()$
windowrule = float on, match:class ^(steam)$, match:title ^(Friends List)$
windowrule = immediate on, match:class ^(steam_app_[0-9]+)$
windowrule = idle_inhibit always, match:class ^(steam_app_[0-9]+)$

workspace = w[tv1], gapsout:$singleWindowGapsOut
workspace = f[1], gapsout:$singleWindowGapsOut

layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar
layerrule = blur on, match:namespace fuzzel
layerrule = ignore_alpha 0.5, match:namespace fuzzel
