$bg_night = rgb(1a1b26)
$bg_storm = rgb(24283b)
$blue     = rgb(7aa2f7)
$purple   = rgb(bb9af7)
$cyan     = rgb(73daca)
$red      = rgb(f7768e)
$slate    = rgb(565f89)

$active_border = $blue $purple 45deg
$inactive_border = rgba(565f8966)
