$bg_night        = rgb(1a1b26)
$bg_storm        = rgb(24283b)
$blue            = rgb(7aa2f7)
$purple          = rgb(bb9af7)
$cyan            = rgb(73daca)
$red             = rgb(f7768e)
$slate           = rgb(565f89)

$orange          = rgb(ff9e64)
$yellow          = rgb(e0af68)
$beige           = rgb(cfc9c2)
$green           = rgb(9ece6a)
$teal            = rgb(73daca)
$cyan_pale       = rgb(b4f9f8)
$cyan_bright     = rgb(2ac3de)
$cyan_dim        = rgb(41a6b5)
$blue_sky        = rgb(7dcfff)
$lavender        = rgb(c0caf5)
$grey_blue       = rgb(a9b1d6)
$grey_muted      = rgb(9aa5ce)
$storm           = rgb(414868)
$operator        = rgb(89ddff)
$punctuation     = rgb(9abdf5)
$doc             = rgb(6f7bb0)

$active_border   = $blue $purple 45deg
$inactive_border = rgba(565f8966)
