env = HYPRCURSOR_THEME,Main
env = HYPRCURSOR_SIZE,24

env = XCURSOR_THEME,Main
env = XCURSOR_SIZE,24

cursor {
    no_hardware_cursors = false
    enable_hyprcursor = true
    sync_gsettings_theme = true
}

