source = $HOME/.config/hypr/colors.conf

$fn_greet = echo "<i> Hi $USER :) </i>"
$wall = $HOME/Pictures/Wallpapers/theme.jpg

general {
  no_fade_in = true
  grace = 1
  disable_loading_bar = false
  hide_cursor = true
  ignore_empty_input = true
  text_trim = true
}

background {
    monitor =
    path = $wall
    color = $bg_night
    blur_passes = 4
    contrast = 0.8916
    brightness = 0.7172
    vibrancy = 0.1696
}

label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H")"
    color = rgba(bb9af7ee)
    font_size = 150
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, -250
    halign = center
    valign = top
    zindex = 5
}

label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    color = rgba(7aa2f7ee)
    font_size = 150
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, -420
    halign = center
    valign = top
    zindex = 5
}

label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %b %A")"
    color = rgba(c0caf5aa)
    font_size = 14
    font_family = JetBrainsMono Nerd Font Mono ExtraBold
    position = 0, -130
    halign = center
    valign = center
    zindex = 5
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2

    outer_color = rgba(122, 162, 247, 0.4) rgba(187, 154, 247, 0.4) 45deg
    inner_color = rgba(26, 27, 38, 0.3)

    font_color = $lavender
    fade_on_empty = true
    placeholder_text = <i></i>

    dots_size = 0.1
    dots_spacing = 1
    dots_center = true
    hide_input = false
    rounding = 12

    position = 0, -370
    halign = center
    valign = center
    zindex = 20

    check_color = rgba(115, 218, 202, 0.5)
    fail_color = rgba(247, 118, 142, 0.5)
}

label {
    monitor =
    text = cmd[update:60000] $fn_greet
    color = rgba(154, 163, 230, 0.6)
    font_size = 17
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, -250
    halign = center
    valign = center
}
