$font = JetBrains Mono Nerd Font

$terminal = kitty
$browser = google-chrome-stable
$editor = nvim
$fileExplorer = yazi

$kbCloseWindow = Super, Q
$kbTerminal = Super, T
$kbBrowser = Super, B
$kbEditor = Super, E
$kbFileExplorer = Super, F
$kbLauncher = Super, Super_L

$volumeStep = 5
$brightnessStep = 5

$windowOpacity = 0.95
$singleWindowGapsOut = 20
