set-option -g default-shell /usr/bin/fish

set -g pane-border-style "fg=#565f89"
set -g pane-active-border-style "fg=#7aa2f7"

set -g pane-border-lines single

set -g message-style "bg=#24283b,fg=#7aa2f7,bold"
set -g message-command-style "bg=#24283b,fg=#bb9af7"

setw -g mode-style "bg=#24283b,fg=#73daca,bold"

set -g popup-border-style "fg=#bb9af7"
set -g popup-border-lines rounded

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g status off

set -g status-style "bg=default"
set -g window-style "bg=default"
set -g window-active-style "bg=default"

setw -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

bind-key -r f display-popup -E -w 80% -h 60% "tmux-sessionizer"
bind r source-file ~/.tmux.conf \; display "Tmux reloaded!"

set -s command-alias[10] q='kill-pane'
set -s command-alias[11] 'q!'='kill-pane'
set -s command-alias[12] qa='kill-session'

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"

bind-key -n 'M-h' if-shell "$is_vim" 'send-keys M-h'  'select-pane -L'
bind-key -n 'M-j' if-shell "$is_vim" 'send-keys M-j'  'select-pane -D'
bind-key -n 'M-k' if-shell "$is_vim" 'send-keys M-k'  'select-pane -U'
bind-key -n 'M-l' if-shell "$is_vim" 'send-keys M-l'  'select-pane -R'

bind-key -n 'M-\' if-shell "$is_vim" 'send-keys M-\\' 'select-pane -l'

bind -n M-q kill-pane

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
