bindr = $kbLauncher, exec, rofi -show drun # Open app launcher

bind = Super, grave, hyprexpo:expo, toggle # Toggle workspace overview
bind = Super, V, exec, cliphist list | fuzzel --dmenu | cliphist decode | wl-copy # Open clipboard history
bind = Super, D, fullscreen, 0 # Toggle fullscreen
bind = Super, P, pin # Pin window on top
bind = Super, left, movefocus, l # Focus left
bind = Super, right, movefocus, r # Focus right
bind = Super, up, movefocus, u # Focus up
bind = Super, down, movefocus, d # Focus down

bindm = Super, mouse:272, movewindow # Move window
bindm = Super, mouse:273, resizewindow # Resize window

bind = Super, 1, workspace, 1 # Switch to workspace 1
bind = Super, 2, workspace, 2 # Switch to workspace 2
bind = Super, 3, workspace, 3 # Switch to workspace 3
bind = Super, 4, workspace, 4 # Switch to workspace 4
bind = Super, 5, workspace, 5 # Switch to workspace 5
bind = Super, 6, workspace, 6 # Switch to workspace 6
bind = Super, 7, workspace, 7 # Switch to workspace 7
bind = Super, 8, workspace, 8 # Switch to workspace 8
bind = Super, 9, workspace, 9 # Switch to workspace 9
bind = Super, 0, workspace, 10 # Switch to workspace 10

bind = Super ALT, 1, movetoworkspace, 1 # Move window to workspace 1
bind = Super ALT, 2, movetoworkspace, 2 # Move window to workspace 2
bind = Super ALT, 3, movetoworkspace, 3 # Move window to workspace 3
bind = Super ALT, 4, movetoworkspace, 4 # Move window to workspace 4
bind = Super ALT, 5, movetoworkspace, 5 # Move window to workspace 5
bind = Super ALT, 6, movetoworkspace, 6 # Move window to workspace 6
bind = Super ALT, 7, movetoworkspace, 7 # Move window to workspace 7
bind = Super ALT, 8, movetoworkspace, 8 # Move window to workspace 8
bind = Super ALT, 9, movetoworkspace, 9 # Move window to workspace 9
bind = Super ALT, 0, movetoworkspace, 10 # Move window to workspace 10
bind = Super, mouse_down, workspace, -1 # Previous workspace (scroll)
bind = Super, mouse_up, workspace, +1 # Next workspace (scroll)

binde = Super, Page_Up, workspace, -1 # Previous workspace
binde = Super, Page_Down, workspace, +1 # Next workspace
binde = Super CTRL, left, workspace, -1 # Previous workspace
binde = Super CTRL, right, workspace, +1 # Next workspace
binde = Super CTRL, up, workspace, +1 # Next workspace
binde = Super CTRL, down, workspace, -1 # Previous workspace

bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle # Toggle mute
bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ $volumeStep%+ # Volume up
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ $volumeStep%- # Volume down
bindl = , XF86MonBrightnessUp, exec, brightnessctl set $brightnessStep%+ # Brightness up
bindl = , XF86MonBrightnessDown, exec, brightnessctl set $brightnessStep%- # Brightness down

bindl = , Print, exec, grim ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png # Screenshot fullscreen
bind = Super SHIFT, S, exec, grim -g "$(slurp)" - | swappy -f - # Screenshot selection

bind = $kbTerminal, exec, $terminal # Open terminal
bind = $kbBrowser, exec, $browser # Open browser
bind = $kbFileExplorer, exec, $terminal -e $fileExplorer # Open file explorer

bind = $kbEditor, exec, $terminal -e $editor # Open editor
bind = Super, W, exec, $browser # Open browser
bind = Super, Q, killactive # Close window
bind = Super, H, exec, ~/.config/hypr/scripts/keybinds.sh
