bindr = $kbLauncher, exec, pkill fuzzel || fuzzel
bind = Super, V, exec, cliphist list | fuzzel --dmenu | cliphist decode | wl-copy

bind = $kbCloseWindow, killactive,
bind = $kbToggleWindowFloating, togglefloating,
bind = Super, F, fullscreen, 0
bind = Super, P, pin

bind = Super, left, movefocus, l
bind = Super, right, movefocus, r
bind = Super, up, movefocus, u
bind = Super, down, movefocus, d

bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow

bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9
bind = Super, 0, workspace, 10

bind = Super SHIFT, 1, movetoworkspace, 1
bind = Super SHIFT, 2, movetoworkspace, 2
bind = Super SHIFT, 3, movetoworkspace, 3
bind = Super SHIFT, 4, movetoworkspace, 4
bind = Super SHIFT, 5, movetoworkspace, 5
bind = Super SHIFT, 6, movetoworkspace, 6
bind = Super SHIFT, 7, movetoworkspace, 7
bind = Super SHIFT, 8, movetoworkspace, 8
bind = Super SHIFT, 9, movetoworkspace, 9
bind = Super SHIFT, 0, movetoworkspace, 10

bind = Super, mouse_down, workspace, -1
bind = Super, mouse_up, workspace, +1
binde = Super, Page_Up, workspace, -1
binde = Super, Page_Down, workspace, +1

bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ $volumeStep%+
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ $volumeStep%-

bindl = , XF86MonBrightnessUp, exec, brightnessctl set $brightnessStep%+
bindl = , XF86MonBrightnessDown, exec, brightnessctl set $brightnessStep%-

bindl = , Print, exec, grim ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png
bind = Super SHIFT, S, exec, grim -g "$(slurp)" - | swappy -f -

bind = $kbTerminal, exec, $terminal
bind = $kbBrowser, exec, $browser
bind = $kbFileExplorer, exec, $terminal -e $fileExplorer
bind = $kbEditor, exec, $terminal -e $editor
